env_flag            = "ENV_TYPE"
tag_env             = "ENV_TYPE"
region              = "REGION"
client		    = "CLIENT_NAME"
tf_state_bucket	    = "BUCKET_NAME"
resource_tag	    = "CLIENT_NAME"
tf_state_bucket_region  = "TF_BUCKET_REGION"
