env_flag     = "ENV_TYPE"
region       = "REGION"
client       = "CLIENT_NAME"
key_name     = "CLIENT_NAME-golden-key"
path         = "/root/client-keys"
resource_tag = "CLIENT_NAME"
tf_state_bucket_region  = "TF_BUCKET_REGION"
